"""Add image_version column to User model for cache busting

Revision ID: 332b93554d25
Revises: 
Create Date: 2025-11-10 18:46:15.403579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332b93554d25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_version')

    # ### end Alembic commands ###
